import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/ui/ThemeProvider'
import ClientProvider from '@/components/ui/ClientProvider'
import FirebaseAuthProvider from '@/components/ui/FirebaseAuthProvider'
import SubscriptionProvider from '@/components/ui/SubscriptionProvider'


export const metadata: Metadata = {
  title: 'LangChat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClientProvider>
      <html lang="en">
        <body className="flex flex-col min-h-screen">
          <FirebaseAuthProvider>
            <SubscriptionProvider>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />

            {children}
            
             </ThemeProvider>
           </SubscriptionProvider>
          </FirebaseAuthProvider>
        </body>
      </html>
    </ClientProvider>
  )
}
